version: "3.9"
services:
  app:
    image: fbricon/vscode-marketplace-stats
    environment:
      - TOKEN=test
      - QUARKUS_DATASOURCE_USERNAME=postgresql
      - QUARKUS_DATASOURCE_PASSWORD=postgresql
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://database:5432/vscode-marketplace-stats
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=vscode-marketplace-stats
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d vscode-marketplace-stats -U postgresql"]
      interval: 3s
      timeout: 5s
      retries: 5