name: Publish Docker image

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE.txt'
      - 'deploy-to-openshift.sh'
      - 'docker-compose.yaml'
    branches:
      - 'main'

jobs:
  publish:
    name: Build and publish Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'maven'

      - name: Build
        run: |
          ./mvnw -e -B -DskipTests=true clean package -Dnative

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          IMAGE_TAG=$(git rev-parse --short=7 HEAD)
          docker build -f src/main/docker/Dockerfile.native -t fbricon/vscode-marketplace-stats:latest .
          docker tag fbricon/vscode-marketplace-stats:latest fbricon/vscode-marketplace-stats:${IMAGE_TAG}
          docker push fbricon/vscode-marketplace-stats:latest
          docker push fbricon/vscode-marketplace-stats:${IMAGE_TAG}